version: "3"

tasks:
  tidy:
    cmds:
      - poetry run ruff check
      - poetry run ruff format
  publish:
    cmds:
      - poetry build
      - poetry publish
  test:
    cmds:
      - pytest tests -v
